name: PUM

channels:
  - pytorch
  - defaults

dependencies:
  - ipython=7.31.1
  - matplotlib=3.7.1
  - pandas=2.2.2
  - pip=24.2
  - python=3.10.12
  - scikit-learn=1.5.1
  - conda-forge::jupyterlab=3.6.8
  - scipy=1.13.1
  - pytorch=2.4.1
  - xgboost=2.1.1
  - seaborn=0.13.2
  - pip:
      - optuna==4.0.0
      - lightgbm==4.5.0
      - librosa==0.10.2
      - pydub==0.25.1
      - opensmile==2.5.0
      - sox==1.5.0
